Code/S04&S05/Projects/SecondProject/Models/News.cs
namespace SecondProject.Models
{
    public class News
    {
        public string Title { get; set; } = string.Empty;
        public string Author { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
    }
}

Code/S04&S05/Projects/SecondProject/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace SecondProject.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Article(string slug)
        {
            return Ok($"Blog > Article: {slug}");
        }
    }
}

Code/S04&S05/Projects/SecondProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SecondProject.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Code/S04&S05/Projects/SecondProject/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using SecondProject.Models;

namespace SecondProject.Controllers;

[Route("News")]
public class NewsController : Controller
{
    [Route("List")]
    public IActionResult Index()
    {
        return Ok("News > List");
    }

    /*
     * Model Binding
     * 
     * HTML Form = Method = GET | POST
     * ?title=xyz&message=xyz (80k char limit)
     * 
     * Form: title=xyz&message=xyz
     */
    [HttpGet("Add")]
    public IActionResult AddGet([FromQuery] News news)
    {
        return Ok();
    }
    [HttpPost("Add")]
    public IActionResult AddPost([FromHeader] string authorization, [FromForm] News news)
    {
        return Ok();
    }

    [HttpPost("Edit/{id}")]
    public IActionResult Edit(int id, [FromBody] News json)
    {
        return Ok($"News > Edit: {id}");
    }
}

Code/S04&S05/Projects/SecondProject/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;
using SecondProject.Models;

namespace SecondProject.Controllers
{
    public class PageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PassData()
        {
            /*
             * Request/Response
             * ViewBag - Dynamic
             * ViewData - Dictonary
             * 
             * Request/Response > Redirect
             * TempData - Dictonary
             */

            ViewBag.Company = "Microsoft";
            ViewBag.Founder = "Bill Gates";
            ViewBag.CEO = "Satya Nadella";

            ViewData["Company2"] = "Apple";
            ViewData["Founder2"] = "Steven Jobs & Steve Wozniak";
            ViewData["CEO2"] = "Tim Cook";


            TempData["Company"] = "Oracle";
            TempData["Founder"] = "Larry Ellison";
            TempData["CEO"] = "Safra A. Catz";

            /*
             * For Test TempData enable this line: return RedirectToAction("ViewTempData");
             */
            

            var news = new News { Title = "News of now", Author="Elias", Message="Good day!" };
            return View(news);
        }

        public IActionResult ViewTempData()
        {
            return Ok($"{TempData.Peek("Company")} - {TempData["Founder"]} - {TempData["CEO"]}");
        }

        public IActionResult Flow()
        {
            List<News> news = new List<News>();
            /*news.Add(new News { Title = "News of now 1", Author = "Elias 1", Message = "Good day!" });
            news.Add(new News { Title = "News of now 2", Author = "Elias 2", Message = "Good day!" });
            news.Add(new News { Title = "News of now 3", Author = "Elias 3", Message = "Good day!" });
            news.Add(new News { Title = "News of now 4", Author = "Elias 4", Message = "Good day!" });
            */
            return View(news);
        }
    }
}

Code/S04&S05/Projects/SecondProject/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace SecondProject.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Code/S04&S05/Projects/SecondProject/Controllers/ResultTypeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SecondProject.Controllers;

[Route("ResultType")]
public class ResultTypeController : Controller
{
    [Route("Content")]
    public IActionResult ContentResult()
    {
        return Content("This is content result 2", "text/plain");

        return new ContentResult
        {
            StatusCode = 200,
            ContentType = "text/plain",
            Content = "This is content result"
        };
    }

    [Route("Json")]
    public IActionResult JsonResult()
    {
        var obj = new { title = "XYZ", content = "XYZ-Content" };

        return Json(obj);

        return new JsonResult(obj);
    }

    [Route("File-Virtual")]
    public IActionResult FileVirtual()
    {
        return File("Files/articles.pdf", "application/pdf");

        return new VirtualFileResult("Files/articles.pdf", "application/pdf");
    }
    [Route("File-Physical")]
    public IActionResult FilePhysical()
    {
        return PhysicalFile(@"C:\Users\elias\Downloads\article.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");

        return new PhysicalFileResult(@"C:\Users\elias\Downloads\article.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    }
    [Route("File-Content")]
    public IActionResult FileContent()
    {
        byte[] fileInBytes = System.IO.File.ReadAllBytes(@"C:\Users\elias\Downloads\articles.pdf");

        return File(fileInBytes, "application/pdf");
        return new FileContentResult(fileInBytes, "application/pdf");
    }

    [Route("View")]
    public IActionResult ViewResult()
    {
        return View("View2");
        return new ViewResult { ContentType = "text/html", ViewName = "ViewResult" };
    }
    
    [Route("Redirect")]
    public IActionResult RedirectResult()
    {
        return Redirect("https://www.google.com");
        return new RedirectResult("https://www.google.com");
    }
    
    [Route("Redirect-Local")]
    public IActionResult RedirectLocalResult()
    {
        return LocalRedirect("/ResultType/View");
        return new LocalRedirectResult("/ResultType/View");
    }
    
    [Route("Redirect-Action")]
    public IActionResult RedirectActionResult()
    {
        var controller = nameof(ResultTypeController).Replace("Controller", string.Empty);
        var action = nameof(ContentResult).Replace("Result", string.Empty);

        return RedirectToAction(action, controller, new { slug = "slug1" });
        return new RedirectToActionResult("Json", "ResultType", new { slug = "slug1" });
    }
}

Code/S04&S05/Projects/SecondProject/Libraries/ViewComponents/AdsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SecondProject.Libraries.ViewComponents;

public class AdsViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(string title)
    {
        //TODO - Get List from Database
        var ads = GetAdsFromDatabase();
        return View(ads);
    }

    public List<Ads> GetAdsFromDatabase()
    {
        List<Ads> ads = new List<Ads>();
        ads.Add(new Ads() { Title = "Ads 1", Description = "Lorem 1....." });
        ads.Add(new Ads() { Title = "Ads 2", Description = "Lorem 2....." });
        ads.Add(new Ads() { Title = "Ads 3", Description = "Lorem 3....." });

        return ads;
    }
}
public class Ads
{
    public string Title { get; set; }
    public string Description { get; set; }
}

Code/S04&S05/Projects/SecondProject/Views/Home/Index.cshtml
@addTagHelper *, SecondProject
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	//Layout = "_Layout";

	ViewBag.Title = "Home - Index";
}



@*
  Razor = Engine Template
*@

<h4>Page</h4>
<a href="/Page/Flow">Flow</a>
<a href="/Page/Index">Index</a>
<a href="/Page/PassData">PassData</a>



@section ads {
	<vc:ads title="Hello" />

	@* @await Component.InvokeAsync("Ads", new { title = "Hello"}) *@

}

Code/S04&S05/Projects/SecondProject/Views/Page/Flow.cshtml
@{
	ViewBag.Title = "Page - Flow";
}
@using SecondProject.Models
@model List<News>

@if(Model is not null && Model.Count > 0)
{
	//algoritm
	// Razor - Literal
	<table>
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Message</th>
		</tr>
		@foreach (var news in Model)
		{
			<tr>
				<td>@news.Title</td>
				<td>@news.Author</td>
				<td>@news.Message</td>
			</tr>
		}
	</table>
}
else
{
	@:No register
	@*
		<text>elias.ribeiro.s@gmail.com</text>
		<span>No register</span>
	*@
}

Code/S04&S05/Projects/SecondProject/Views/Page/Index.cshtml
@*
	Razor - Comment
	Razor (pre-compilado) - JIT
*@
@{
	// Block of C#
	/**/
	string dt = DateTime.Now.ToString("MM/dd/yyyy HH:mm:ss");
	string name = "Elias Ribeiro da Silva Costa";
	int result = 40 * 3 * 2 * 9 / 4 + 30;
}
<html>
<head>

</head>
<body>
	<h1>Hello world!</h1>
	<p>xyz...</p>
	<p>Name: @name</p>
	<p>40 * 3 * 2 * 9 / 4 + 30 = @result</p>
	<p>Now: @dt</p>
</body>
</html>

Code/S04&S05/Projects/SecondProject/Views/Page/PassData.cshtml
@model News

<h1>Model</h1>
<h2>@Model.Title</h2>
<h4>@Model.Author</h4>
<p>
	@Model.Message
</p>
<hr />
<h1>ViewBag</h1>
<p>
	Company: @ViewBag.Company
	<br />
	Founders: @ViewBag.Founder
	<br />
	CEO: @ViewBag.CEO
</p>

<hr />
<h1>ViewData</h1>
<p>
	Company: @ViewData["Company2"]
	<br />
	Founders: @ViewData["Founder2"]
	<br />
	CEO: @ViewData["CEO2"]
</p>

<hr />
<h1>TempData</h1>
<p>
	Company: @TempData["Company"]
	<br />
	Founders: @TempData["Founder"]
	<br />
	CEO: @TempData["CEO"]
</p>

Code/S04&S05/Projects/SecondProject/Views/ResultType/View2.cshtml
<h1>View 2</h1>

Code/S04&S05/Projects/SecondProject/Views/ResultType/ViewResult.cshtml
<h1>View</h1>

Code/S04&S05/Projects/SecondProject/Views/Shared/Components/Ads/Default.cshtml
@model List<SecondProject.Libraries.ViewComponents.Ads>
<h1>Ads</h1>
@foreach (var ad in Model)
{
	<div>
		<h3>@ad.Title</h3>
		@ad.Description
	</div>
}

Code/S04&S05/Projects/SecondProject/Views/Shared/_Footer.cshtml
@model string
<footer style="background-color: lightgreen;padding: 12px;">
	<div class="row">
		<div class="col">
			@Html.Raw(Model)
		</div>
		<div class="col">
			@ViewData["Company"]
		</div>
	</div>
	
	@* Copyright *@
	@* Company *@
	@* Author *@
</footer>

Code/S04&S05/Projects/SecondProject/Views/Shared/_Header.cshtml
<header style="background-color: lightgreen; padding: 12px;">
	Header > @ViewBag.Title
</header>

Code/S04&S05/Projects/SecondProject/Views/Shared/_Layout.cshtml
@using System.IO;
@using System.Text.Encodings.Web;
@{
	var htmlContent = await Html.PartialAsync("~/Views/Shared/_Header.cshtml");

	string html;
	using(var sw = new StringWriter())
	{
		htmlContent.WriteTo(sw, HtmlEncoder.Default);
		html = sw.ToString();

		html = html.Replace(" > ", " : ");
	}

	string copyright = $"Copyright &copy; All right reserved - {DateTime.Now.Year}";
	string company = "Microsoft";
}
<!DOCTYPE html>
<html>
<head>
	<title>@ViewBag.Title</title>
	<!--CSS, JS, Meta-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>
<body>
	<div class="container-fluid" style="padding: 0px;">
		@await Html.PartialAsync("~/Views/Shared/_Header.cshtml")
		@*
			@Html.Raw(html)
			@{
				await Html.RenderPartialAsync("~/Views/Shared/_Header.cshtml");
			}
		*@
		<div>
			<div class="row" style="background-color: #FFDAB9; padding: 12px;">
				<div class="col-8">
					@RenderBody()
				</div>
				<div class="col-4">
					@RenderSection("ads", required: false)
				</div>
			</div>
		</div>
		<!-- ASP.NET MVC - Enable Tag Helper -->
		<partial name="~/Views/Shared/_Footer.cshtml" model="copyright" view-data="ViewData" view-data-Company="company" />

		@*
			await Html.PartialAsync("~/Views/Shared/_Footer.cshtml", copyright, new ViewDataDictionary(ViewData) { { "Company", "Microsoft" } });
		*@

	</div>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
	@RenderSection("scripts", required: false)
</body>
</html>

Code/S04&S05/Projects/SecondProject/Views/Shared/_ProfileLayout.cshtml
@{
	Layout = "_Layout";
}
<div class="row">
	<div class="col-4">
		<nav style="background-color: limegreen">
			<h3>ProfileLayout</h3>
			<ul>
				<li>Update profile</li>
				<li>Update address</li>
				<li>Change password</li>
			</ul>
		</nav>
	</div>
	<div class="col-8">
		@RenderBody()
	</div>
</div>